name: drupal
apiVersion: v2
type: application
version: 0.8.2
appVersion: 1.0.0
description: Drupal 8/9.
keywords:
- drupal
- cms
- http
- web
- application
- php
home: https://bitbucket.org/kohler_source/jacob-delafon-devops
icon: https://bitnami.com/assets/stacks/drupal/img/drupal-stack-220x234.png
sources:
- https://bitbucket.org/kohler_source/jacob-delafon-devops
maintainers:
- name: shutov
  email: Andrii_Shutov@epam.com
engine: gotpl
dependencies:
  - name: mysql
    version: 1.6.2
    repository: https://charts.helm.sh/stable
    condition: mysql.enabled
  - name: postgresql
    version: 8.6.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 11.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: varnish
    version: 0.1.5
    repository: https://statcan.github.io/charts
    condition: varnish.enabled
