{{- if .Values.azureFile.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
{{- if .Values.azureFile.enabled }}
{{ toYaml .Values.azureFile.annotations | indent 4 }}
{{- end }}
  name: {{ include "drupal.fullname" . }}-public
spec:
  accessModes:
    - {{ .Values.azureFile.accessMode }}
  resources:
    requests:
      storage: {{ .Values.azureFile.size }}
  volumeName: {{ include "drupal.fullname" . }}-public
{{- if eq "-" .Values.azureFile.storageClass }}
  storageClassName: ""
{{- else if .Values.azureFile.storageClass }}
  storageClassName: "{{ .Values.azureFile.storageClass }}"
{{- end }}
{{- end }}
