{{- if .Values.efs.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
{{- if .Values.efs.enabled }}
{{ toYaml .Values.efs.annotations | indent 4 }}
{{- end }}
  name: {{ include "drupal.fullname" . }}-private
spec:
  accessModes:
    - {{ .Values.efs.accessMode }}
  resources:
    requests:
      storage: {{ .Values.efs.size }}
  volumeName: {{ include "drupal.fullname" . }}-private
{{- if eq "-" .Values.efs.storageClass }}
  storageClassName: ""
{{- else if .Values.efs.storageClass }}
  storageClassName: "{{ .Values.efs.storageClass }}"
{{- end }}
{{- end }}
